### ISSUE TITLE
Using OBS plugins

### ISSUE THREAD

**Issue by viral98** [Envek/obs-studio-node-example#11]
Hey! Is there a way through which I can use OBS plugins like virtual camera through nodeobs?

**Comment by Envek** [comment]
Take a look at this obs-studio-node's test: it looks like plugins initialization: https://github.com/stream-labs/obs-studio-node/blob/2cf61ea8d18839cbe919a5f03db76db5e5da36f5/tests/osn-tests/src/test_osn_module.ts
And here is the path where plugins are searched for: https://github.com/stream-labs/obs-studio-node/blob/d54a2828247fbbb4704fc44089bcfcd78966966c/js/module.js#L11

Please tell us a bit more about plugins you're interested in: how to get and install them, how to use them in OBS?

**Comment by viral98** [comment]
I wanted to try out the plugin which initializes [virtual camera](https://obsproject.com/forum/resources/obs-virtualcam.949/)
Thanks for the links though, I'll check them out! Appreciate it!

**Comment by Envek** [comment]
@viral98, have you figured it out? Can you share your solution with us?

**Comment by viral98** [comment]
Hey - no, it seems like I will have to wait till the node OBS team develops it - they seem to be forking webcamdoid's virtual device drivers to [generate one for their own system](https://howto.streamlabs.com/streamlabs-obs-9/how-to-install-virtualcam-on-zoom-with-streamlab-14764). As of now, its Mac only.
