### ISSUE TITLE
Audio output

### ISSUE THREAD

**Issue by hrueger** [Envek/obs-studio-node-example#13]
And idea how I can output audio?
When I create a video source like [here](https://github.com/hrueger/obs-studio-node/blob/added-docs/README.md), I can't hear any sound.

**Comment by Envek** [comment]
Do you want to output audio to recorded file or do you want to play sound via speakers when program runs?

For the first case, current version records system audio to file together with microphone capture:
https://github.com/Envek/obs-studio-node-example/blob/65d587ba64fe19fbfbb50ecb3ba423d51fb273ef/obsRecorder.js#L184-L190
Try to record while watching some video or playing games _and_ speaking at the same time: you will hear both yourself and video/game sound.

**Comment by hrueger** [comment]
I want to output audio speakers while my video source is playing, so the second case.
I wasn't able to find that part in `streamlabs-obs`...

**Comment by Envek** [comment]
And what audio do you want to play? Static files? Another stream? May be it is better to use built-in Electron features for that? :thinking:

**Comment by hrueger** [comment]
My application [AGView](https://github.com/hrueger/AGView) is a slide based video player. Like in PowerPoint you have all the slides and when you click one of them, the second screen or projector window fades over to this video and plays it.
The video files are playing without problems and even the transitions are working fine. I just don't hear the sound of the video files.

I belive we have to "tell" osn which speaker / output to use?

**Comment by emptycrown** [comment]
If you open the video files themselves and there is no audio, that essentially means something went wrong when capturing audio in the first place. I would check to make sure your audio sources and/or mic sources were set up correctly.

If the video files have audio but you just can't hear anything when the app is running, that sounds like it's not an OBS issue and something up with the app itself. For example, you can check if there's sound when you simply mount it in a `<video>` element.

**Comment by hrueger** [comment]
The video files do have audio. Playing them in the electron window with a `<video>` tag also works fine and I can hear sound.
I found the `volume` property of the `IInput` objects, but no matter to what value I set it, I can't hear anything...

**Comment by hrueger** [comment]
Thanks to @alokmahor we now kow that you need to set `source.monitoringType` to `2` in order to hear sound. See  https://github.com/hrueger/AGView/pull/38 for reference. I'll keep investigating and add that to https://github.com/hrueger/obs-studio-node-docs . I'll close this issue once the documentation is in place.

**Comment by hrueger** [comment]
added docs in https://github.com/hrueger/obs-studio-node-docs/commit/9e9285106cc4450506fffee594693d5834a2f386
There are three options available in total, provided by the `osn.EMonitoringType` enum.
