### ISSUE TITLE
Unable to set webcam resolution

### ISSUE THREAD

**Issue by berkon** [Envek/obs-studio-node-example#31]
I'v removed the comments in the corresponding section in obsRecorder.js, and set the resolution to 1920x1080, but the webcam still shows 640x480. Also setting width and height in `InputFactory.create(...)` does not seem to change anything.

```
// Way to update settings if needed:
let settings = obsCameraInput.settings;
console.debug('Camera settings:', obsCameraInput.settings);
settings['width'] = 1920;
settings['height'] = 1080;
obsCameraInput.update(settings);
obsCameraInput.save();
```

BTW: Thanks for this great example @Envek. This helped me a lot. Unfortunately obs-studio-node is not documented very well.

**Comment by berkon** [comment]
Just found the solution:
```
// Way to update settings if needed:
let settings = obsCameraInput.settings;
console.debug('Camera settings:', obsCameraInput.settings);
settings['res_type'] = 1
settings['resolution'] = "1920x1080",
obsCameraInput.update(settings);
obsCameraInput.save();
```

**Comment by Envek** [comment]
> Unfortunately obs-studio-node is not documented very well.

That's why we've created this example, after all.

Thank you for sharing the solution! I've added it to README

**Comment by xueshuaichao** [comment]
I tried,but it not work.
