### ISSUE TITLE
Add docs to this repo

### ISSUE THREAD

**Issue by hrueger** [Envek/obs-studio-node-example#35]
As you might know, I created this PR https://github.com/stream-labs/obs-studio-node/pull/658 back in May 2020.
Since they seem to ignore it, should we add it to this repo in a `docs` folder?

**Comment by Envek** [comment]
I don't see much value in the whole library docs here. However, some README pieces (like “how to do X”) looks pretty valuable and I would like to have them in our example's README.

Feel free to create pull request and add or change anything in our README ghat makes sense for you.

**Comment by hrueger** [comment]
OK, sure. Makes sense. If I create a docs repo under my scope, would you link to it?

**Comment by Envek** [comment]
Yes, sure.
