### ISSUE TITLE
Padding bars around display

### ISSUE THREAD

**Issue by hrueger** [Envek/obs-studio-node-example#8]
I needed to remove the padding around the display, because my display is in a fullscreen window and the bars make it scale down just a bit, so it is blurry...
This can be done with: `osn.NodeObs.OBS_content_setPaddingSize(displayId, 0);`.
Should we add this to the example app @Envek ?

**Comment by Envek** [comment]
Can't really understand why this padding appears on the first place… But yes, feel free to add it and make a pull request!
